name: "Build"
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Build Add-on"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: .

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: target.xpi
          path: ${{ steps.web-ext-build.outputs.target }}
